<html>
    <head>  
        <title> Calculator</title>
    
    <script language ="javascript" type="text/javascript">
    
    function subTotal ()  {
        
        var x = 5 ;
        var y = 10;
        var p = x + y * 12;
        var b = y * 12;
        
        if (document.getElementById('basicProgram').checked)   {
            document.calculator.total.value = b;
     
        } else if ()
        
    }
   
</html>
